### ISSUE TITLE
feature suggestions

### ISSUE THREAD

**Issue by davidm-public** [asvae/vue-component-tree#1]
Hi, am looking at this project as an alternative to Storybook, which doesnt work well with VueDevtools, apparently because it uses an iframe.

One thing I've noticed is that vue-component-tree has significant performance issues when the number of components increases, far worse performance than storybook with the same number of components.

So, am wondering if there is a programmatic way to 'v-if' all of the non-selected components so that they don't consume resources?

One thought is to watch the url, another is to have register a callback which gets the 'selected component'.

Thougts?

**Comment by asvae** [comment]
Hi. Sorry for late answer.

> when the number of components increases
Can you elaborate on that? In my project I have ~600 demo components. And I didn't notice any performance issues apart from slight list lag on search.

> if there is a programmatic way to 'v-if'
We'll see when I reproduce the issue at hand.
